### PR TITLE
WIP: Initial concept for the list of themes

### PR DESCRIPTION
**Pull request by parkr**
Going with a grid for now, but it'd be cool to have a concept where we have full-page screenshots that overlay like a flipbook where you can see a flap of each, but when hovered over, shows it mostly full screen (move other themes' screenshots to the edge)

### CODE REVIEW

**Comment by parkr** [comment]
## Homepage

screen shot 2014-04-24 at 11 12 13 am

## Theme page

screen shot 2014-04-24 at 11 12 04 am

## Thoughts?

Ok, I think it's ready for a bit of review. Perhaps @cobyism could be the kindest gentleman and take a gander? Also @benbalter, if you have a cycle, a :+1: would be solid. :heart:

**Comment by ndarville** [comment]
The main thing I want in a “theme garden” are some filters to sort by:
- Responsive
- Print.css
- Browser support
- Relies on fonts that work across platforms (i.e. not Helvetica/Calibri, etc.)
- Stylesheet coded in SASS vs. LESS vs. CSS

Just to name some examples.

This is particularly relevant, when the number of themes grows to the size of [Ghost’s](http://marketplace.ghost.org/).

I also have [a Jekyll boilerplate repo](https://github.com/FranklyWeb/jekyll-boilerplate) with a Travis script to lint the CSS, HTML, and JS, if applying that to the submissions is of any interest. The script doesn’t return error codes—i.e. merge-request failures—for the time being, though. 

PS: How pluggable should we make theming of syntax-highlighting, come to think of it?

**Comment by doktorbro** [comment]
@parkr Take a look at Jquery’s [plugin list solution](http://plugins.jquery.com/docs/publish/). The theme author would need a git hook and a [package manifest](http://plugins.jquery.com/docs/package-manifest/).

A theme garden as @ndarville propose is not maintainable.

**Comment by doktorbro** [comment]
The list could contain automatic quality _hints:_
- stars on Github (weak clue)
- last commit date (strong clue)
  - maintained
    
    
  - abandoned (remove from listing after 2 years without updates)

**Pull request closed without merging**
